Traceback (most recent call last):
  File "main.py", line 228, in <module>
    step_metrics = algorithm.update(minibatches_device)
  File "/data/healthy-ml/scratch/olawale/my-icrm/algorithms.py", line 142, in update
    loss = self.loss_func(p, all_y)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1188, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/functional.py", line 3104, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected target size [32, 2], got [32]
